import type { CapacitorConfig } from "@capacitor/cli";

/** Generated by scripts/write-capacitor-config.mjs (production) */
const config: CapacitorConfig = {
  appId: "shop.kioskpos.app",
  appName: "Kiosk POS",
  webDir: "www",
  backgroundColor: "#0a0c12",
  server: {
    url: "https://kioskpos.shop",
    cleartext: false,
    hostname: "kioskpos.shop",
    androidScheme: "https",
    allowNavigation: ["kioskpos.shop","*.kioskpos.shop","kioskpos.shop","accounts.google.com","*.google.com","*.googleusercontent.com","*.supabase.co","supabase.co","10.0.2.2","localhost"],
    errorPath: "index.html",
  },
  android: {
    allowMixedContent: false,
    backgroundColor: "#0a0c12",
    appendUserAgent: "KioskPOS-Native/1.0",
  },
  ios: {
    contentInset: "automatic",
    backgroundColor: "#0a0c12",
    appendUserAgent: "KioskPOS-Native/1.0",
    scrollEnabled: true,
    scheme: "App",
  },
  plugins: {
    SplashScreen: {
      launchAutoHide: false,
      launchShowDuration: 0,
      backgroundColor: "#0a0c12",
      androidSplashResourceName: "splash",
      showSpinner: false,
    },
    StatusBar: {
      style: "DARK",
      backgroundColor: "#0a0c12",
    },
    Keyboard: {
      resize: "body",
      resizeOnFullScreen: true,
    },
    LocalNotifications: {
      smallIcon: "ic_launcher_foreground",
      iconColor: "#6366f1",
      sound: "default",
    },
    Camera: {
      permissions: ["camera"],
    },
  },
};

export default config;
